### ISSUE TITLE
PHP files do not protect against SQL injection

### ISSUE THREAD

**Issue by kcozens** [djphil/osguide#1]
The osguide is looking good for the first release. The PHP files that interact with a SQL database are unsafe to use in a production environment. All data received by the scripts that is used in an SELECT, INSERT, or UPDATE SQL command should be wrapped in mysql_real_escape_string() to avoid possible SQL injection problems.

**Comment by djphil** [comment]
Thank you for reminding me that Plugh, i'll try to improve it.
