### ISSUE TITLE
images

### ISSUE THREAD

**Issue by meme0623** [djphil/osguide#3]
Bonjour Djphil ,

J'ai bien installer le guide des destinations ,cela fonctionne ,sauf que j'arrive pas a comprendre comment récupérer l'image de la region ,je n'ai que no image available

**Comment by djphil** [comment]
Bonjour meme0623 et bienvenue,
- Il faut les créer soi-même et les placer dans le dossier "img".
- La dimension conseillée est celle de default.jpg (700px * 400px).
- Les noms des images sont soit les noms des catégories, soit les noms des régions.

De cette façon tu as le plein controle sur les images affichées.
